### ISSUE TITLE
Normalizar el `datepicker` para todos los navegadores

### ISSUE THREAD

**Issue by IsaacLf** [IsaacLf/itescam-calendar#11]
El `datepicker` se usó en la selección de las fechas de eventos, se encuentra actualmente en la ruta:
```bash
/resources/assets/js/App.vue
```
en el modal `#addNewEvent` en los input `#startDate` y `#endDate`.

Es posible que necesitemos un plugin o algo para que la selección se vea igual en todos los navegadores.

**Comment by IsaacLf** [comment]
@jlirat aquí está la descripción del problema, y para más información sobre qué herramientas se utilizaron está la [Wiki: Cómo contribuir](https://github.com/IsaacLf/itescam-calendar/wiki/C%C3%B3mo-contribuir#prerrequisitos)

**Comment by jlirat** [comment]
Implementado vuejs-datepicker en branch datepicker

**Comment by jlirat** [comment]
Propuesta de prueba para normalizar

**Comment by IsaacLf** [comment]
@jlirat me imagino que está trabajando en su fork que había hecho, debe primero actualizar el repo para que esté parejo con el mío:

![image](https://user-images.githubusercontent.com/36938997/60728576-49e6e680-9f06-11e9-9b39-30e6ed225cf2.png)

Y luego hacer los cambios de prueba en su copia, y de ultimo cuando esté todo probado pedir un "pull request" para mezclar sus cambios a la rama correspondiente de mi repositorio original.

Aunque ya vi que trabajó directamente en mi repo, en la rama "datepicker", Así está bien por ahora.

**Comment by IsaacLf** [comment]
Ya chequé, y se ve bien tanto en Edge como en Chrome:

Chrome:
![image](https://user-images.githubusercontent.com/36938997/60729185-b6aeb080-9f07-11e9-99d4-d37044c40b69.png)

Edge:
![image](https://user-images.githubusercontent.com/36938997/60729156-a7c7fe00-9f07-11e9-9c6c-ad24761f7a7d.png)

Pero hay un problema a nivel funcional: y es que el string que crea el `datepicker` se ve algo así:
![image](https://user-images.githubusercontent.com/36938997/60729257-ea89d600-9f07-11e9-997b-0fe356c47b3a.png)

sin embargo se esperaba recibir de la siguiente manera:
![image](https://user-images.githubusercontent.com/36938997/60729369-20c75580-9f08-11e9-9fc1-5752d71006ac.png)

este puede ser un problema que se solucione con un formateo de fecha, pero es importante recibir la fecha en este formato: `yyyy-MM-dd`

**Comment by jlirat** [comment]
Fíjate que probé el guardar y funciona bien, sin embargo al momento de recuperar la fecha es cuando falla. Tienes implementado alguna conversión en algún lado?

**Comment by IsaacLf** [comment]
Es que cuando guarda, guarda el string como tal; cuando hago la consulta pues ahí si uso la fecha en ese formato, no recuerdo si lo leí en algún lado, pero creo que tenía que guardar la fecha en ese formato para que pueda hacer la consulta desde Eloquent: por ejemplo en el archivo 
```bash
/app/Http/Controllers/EventApiController.php
```
en la función `getPublishedByDate(request)`:
![image](https://user-images.githubusercontent.com/36938997/60735947-e3b88e80-9f1a-11e9-937c-19d4be52e06f.png)

Y también lo uso en el archivo:
```bash
resources/assets/ts/calendar.ts
```
para settear los eventos a mi calendario en la función `setEvents(events)` de la clase `Calendar`:
![image](https://user-images.githubusercontent.com/36938997/60736071-59245f00-9f1b-11e9-9cb3-f377cc58ee0e.png)

**Comment by jlirat** [comment]
En ese de calendar es el problema, en los otros no, porque cuando lo manda ya lo recibe como Fecha.

**Comment by IsaacLf** [comment]
Se puede decir que es un poco rebuscado en dónde llamo al método "getEvents" pero hay un método en el archivo `resources/assets/js/App.vue` y `resources/assets/js/components/frontend/App.vue` que llama a PHP mediante un fetch de JS.
![image](https://user-images.githubusercontent.com/36938997/60736346-40687900-9f1c-11e9-85a6-dc243c056215.png)

y este método `fetchEvents` se llama cada que se cambia el año seleccionado

**Comment by IsaacLf** [comment]
y me acabo de dar cuenta que cuando intento guardar un nuevo evento, usando ese formato, me tira el siguiente error:

![image](https://user-images.githubusercontent.com/36938997/60737092-13699580-9f1f-11e9-91a6-715eceeb9826.png)

que tiene que ver con el formato de la fecha.

**Comment by jlirat** [comment]
Trae correctamente la fecha pero viene agregado la hora, ok, lo checo

**Comment by IsaacLf** [comment]
También si se puede, ponerle un placeholder a la selección para que no se vea muy vacío

**Comment by jlirat** [comment]
Ya está solucionado el formato con el componente moment, se agregó placeholder del formato mostrado, al momento de guardar no valida que tenga datos el campo y no muestra un mensaje de error en caso de fallo.
